In [233]:
import pandas as pd
import numpy as np
from statsmodels.tsa.stattools import adfuller
from pathlib import Path

In [234]:
DATASET_PATH = Path('..\\data\\processed\\master_training_data.csv')

df = pd.read_csv(DATASET_PATH)

C:\Users\thilo\AppData\Local\Temp\ipykernel_20232\495611998.py:3: DtypeWarning: Columns (0: holiday_name, 1: cal_holiday_names, 2: cal_holiday_regions, 3: cal_event_names) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(DATASET_PATH)

In [235]:
df.head(10)

,timestamp,demand_mw,date,hour,day_of_week,day_of_month,month,weekend,season,temperature_2m,...,cal_is_bank_holiday_england_wales,cal_is_bank_holiday_scotland,cal_is_bank_holiday,cal_event_count,cal_event_names,cal_is_covid_lockdown,cal_is_general_election,cal_is_major_football,cal_is_event_day,cal_is_non_working_day
0,2010-01-01 00:00:00,36566.5,2010-01-01,0,4,1,1,0,winter,-0.76,...,0,0,1,0,NaN,0,0,0,0,1
1,2010-01-01 01:00:00,35852.5,2010-01-01,1,4,1,1,0,winter,-1.02,...,0,0,1,0,NaN,0,0,0,0,1
2,2010-01-01 02:00:00,34189.5,2010-01-01,2,4,1,1,0,winter,-1.17,...,0,0,1,0,NaN,0,0,0,0,1
3,2010-01-01 03:00:00,32453.0,2010-01-01,3,4,1,1,0,winter,-1.21,...,0,0,1,0,NaN,0,0,0,0,1
4,2010-01-01 04:00:00,30450.5,2010-01-01,4,4,1,1,0,winter,-1.21,...,0,0,1,0,NaN,0,0,0,0,1
5,2010-01-01 05:00:00,29491.5,2010-01-01,5,4,1,1,0,winter,-1.21,...,0,0,1,0,NaN,0,0,0,0,1
6,2010-01-01 06:00:00,29487.5,2010-01-01,6,4,1,1,0,winter,-1.21,...,0,0,1,0,NaN,0,0,0,0,1
7,2010-01-01 07:00:00,28793.5,2010-01-01,7,4,1,1,0,winter,-1.21,...,0,0,1,0,NaN,0,0,0,0,1
8,2010-01-01 08:00:00,28993.5,2010-01-01,8,4,1,1,0,winter,-1.21,...,0,0,1,0,NaN,0,0,0,0,1
9,2010-01-01 09:00:00,31851.5,2010-01-01,9,4,1,1,0,winter,-1.21,...,0,0,1,0,NaN,0,0,0,0,1

In [236]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 145784 entries, 0 to 145783
Data columns (total 51 columns):
 #   Column                                  Non-Null Count   Dtype
---  ------                                  --------------   -----
 0   timestamp                               145784 non-null  str
 1   demand_mw                               145784 non-null  float64
 2   date                                    145784 non-null  str
 3   hour                                    145784 non-null  int64
 4   day_of_week                             145784 non-null  int64
 5   day_of_month                            145784 non-null  int64
 6   month                                   145784 non-null  int64
 7   weekend                                 145784 non-null  int64
 8   season                                  145784 non-null  str
 9   temperature_2m                          145784 non-null  float64
 10  relative_humidity_2m                    145784 non-null  float64
 11  dew_point_2m                            145784 non-null  float64
 12  apparent_temperature                    145784 non-null  float64
 13  precipitation                           145784 non-null  float64
 14  rain                                    145784 non-null  float64
 15  surface_pressure                        145784 non-null  float64
 16  cloud_cover                             145784 non-null  float64
 17  wind_speed_10m                          145784 non-null  float64
 18  wind_direction_10m                      145784 non-null  float64
 19  shortwave_radiation                     145784 non-null  float64
 20  econ_year                               145784 non-null  int64
 21  econ_month                              145784 non-null  int64
 22  econ_industrial_production_index_lag1m  145784 non-null  float64
 23  econ_gdp_index_lag1m                    145784 non-null  float64
 24  econ_cpi_index_lag1m                    145784 non-null  float64
 25  econ_unemployment_rate_lag1m            145784 non-null  float64
 26  econ_economic_data_complete             145784 non-null  int64
 27  is_holiday                              145784 non-null  int64
 28  holiday_name                            2112 non-null    str
 29  cal_year                                145784 non-null  int64
 30  cal_month_num                           145784 non-null  int64
 31  cal_month_name                          145784 non-null  str
 32  cal_day                                 145784 non-null  int64
 33  cal_day_of_week                         145784 non-null  str
 34  cal_day_of_week_num                     145784 non-null  int64
 35  cal_week_of_year                        145784 non-null  int64
 36  cal_quarter                             145784 non-null  int64
 37  cal_is_weekend                          145784 non-null  int64
 38  cal_season                              145784 non-null  str
 39  cal_holiday_names                       2112 non-null    str
 40  cal_holiday_regions                     2112 non-null    str
 41  cal_is_bank_holiday_england_wales       145784 non-null  int64
 42  cal_is_bank_holiday_scotland            145784 non-null  int64
 43  cal_is_bank_holiday                     145784 non-null  int64
 44  cal_event_count                         145784 non-null  int64
 45  cal_event_names                         4512 non-null    str
 46  cal_is_covid_lockdown                   145784 non-null  int64
 47  cal_is_general_election                 145784 non-null  int64
 48  cal_is_major_football                   145784 non-null  int64
 49  cal_is_event_day                        145784 non-null  int64
 50  cal_is_non_working_day                  145784 non-null  int64
dtypes: float64(16), int64(25), str(10)
memory usage: 56.7 MB

In [237]:
print(df.shape)
print(df.columns)
print(df.dtypes)
print(df.isna().sum())

(145784, 51)
Index(['timestamp', 'demand_mw', 'date', 'hour', 'day_of_week', 'day_of_month',
       'month', 'weekend', 'season', 'temperature_2m', 'relative_humidity_2m',
       'dew_point_2m', 'apparent_temperature', 'precipitation', 'rain',
       'surface_pressure', 'cloud_cover', 'wind_speed_10m',
       'wind_direction_10m', 'shortwave_radiation', 'econ_year', 'econ_month',
       'econ_industrial_production_index_lag1m', 'econ_gdp_index_lag1m',
       'econ_cpi_index_lag1m', 'econ_unemployment_rate_lag1m',
       'econ_economic_data_complete', 'is_holiday', 'holiday_name', 'cal_year',
       'cal_month_num', 'cal_month_name', 'cal_day', 'cal_day_of_week',
       'cal_day_of_week_num', 'cal_week_of_year', 'cal_quarter',
       'cal_is_weekend', 'cal_season', 'cal_holiday_names',
       'cal_holiday_regions', 'cal_is_bank_holiday_england_wales',
       'cal_is_bank_holiday_scotland', 'cal_is_bank_holiday',
       'cal_event_count', 'cal_event_names', 'cal_is_covid_lockdown',
       'cal_is_general_election', 'cal_is_major_football', 'cal_is_event_day',
       'cal_is_non_working_day'],
      dtype='str')
timestamp                                     str
demand_mw                                 float64
date                                          str
hour                                        int64
day_of_week                                 int64
day_of_month                                int64
month                                       int64
weekend                                     int64
season                                        str
temperature_2m                            float64
relative_humidity_2m                      float64
dew_point_2m                              float64
apparent_temperature                      float64
precipitation                             float64
rain                                      float64
surface_pressure                          float64
cloud_cover                               float64
wind_speed_10m                            float64
wind_direction_10m                        float64
shortwave_radiation                       float64
econ_year                                   int64
econ_month                                  int64
econ_industrial_production_index_lag1m    float64
econ_gdp_index_lag1m                      float64
econ_cpi_index_lag1m                      float64
econ_unemployment_rate_lag1m              float64
econ_economic_data_complete                 int64
is_holiday                                  int64
holiday_name                                  str
cal_year                                    int64
cal_month_num                               int64
cal_month_name                                str
cal_day                                     int64
cal_day_of_week                               str
cal_day_of_week_num                         int64
cal_week_of_year                            int64
cal_quarter                                 int64
cal_is_weekend                              int64
cal_season                                    str
cal_holiday_names                             str
cal_holiday_regions                           str
cal_is_bank_holiday_england_wales           int64
cal_is_bank_holiday_scotland                int64
cal_is_bank_holiday                         int64
cal_event_count                             int64
cal_event_names                               str
cal_is_covid_lockdown                       int64
cal_is_general_election                     int64
cal_is_major_football                       int64
cal_is_event_day                            int64
cal_is_non_working_day                      int64
dtype: object
timestamp                                      0
demand_mw                                      0
date                                           0
hour                                           0
day_of_week                                    0
day_of_month                                   0
month                                          0
weekend                                        0
season                                         0
temperature_2m                                 0
relative_humidity_2m                           0
dew_point_2m                                   0
apparent_temperature                           0
precipitation                                  0
rain                                           0
surface_pressure                               0
cloud_cover                                    0
wind_speed_10m                                 0
wind_direction_10m                             0
shortwave_radiation                            0
econ_year                                      0
econ_month                                     0
econ_industrial_production_index_lag1m         0
econ_gdp_index_lag1m                           0
econ_cpi_index_lag1m                           0
econ_unemployment_rate_lag1m                   0
econ_economic_data_complete                    0
is_holiday                                     0
holiday_name                              143672
cal_year                                       0
cal_month_num                                  0
cal_month_name                                 0
cal_day                                        0
cal_day_of_week                                0
cal_day_of_week_num                            0
cal_week_of_year                               0
cal_quarter                                    0
cal_is_weekend                                 0
cal_season                                     0
cal_holiday_names                         143672
cal_holiday_regions                       143672
cal_is_bank_holiday_england_wales              0
cal_is_bank_holiday_scotland                   0
cal_is_bank_holiday                            0
cal_event_count                                0
cal_event_names                           141272
cal_is_covid_lockdown                          0
cal_is_general_election                        0
cal_is_major_football                          0
cal_is_event_day                               0
cal_is_non_working_day                         0
dtype: int64

In [238]:
df.head()

,timestamp,demand_mw,date,hour,day_of_week,day_of_month,month,weekend,season,temperature_2m,...,cal_is_bank_holiday_england_wales,cal_is_bank_holiday_scotland,cal_is_bank_holiday,cal_event_count,cal_event_names,cal_is_covid_lockdown,cal_is_general_election,cal_is_major_football,cal_is_event_day,cal_is_non_working_day
0,2010-01-01 00:00:00,36566.5,2010-01-01,0,4,1,1,0,winter,-0.76,...,0,0,1,0,NaN,0,0,0,0,1
1,2010-01-01 01:00:00,35852.5,2010-01-01,1,4,1,1,0,winter,-1.02,...,0,0,1,0,NaN,0,0,0,0,1
2,2010-01-01 02:00:00,34189.5,2010-01-01,2,4,1,1,0,winter,-1.17,...,0,0,1,0,NaN,0,0,0,0,1
3,2010-01-01 03:00:00,32453.0,2010-01-01,3,4,1,1,0,winter,-1.21,...,0,0,1,0,NaN,0,0,0,0,1
4,2010-01-01 04:00:00,30450.5,2010-01-01,4,4,1,1,0,winter,-1.21,...,0,0,1,0,NaN,0,0,0,0,1

In [239]:
df["timestamp"] = pd.to_datetime(df["timestamp"])
time_diff = df["timestamp"].diff()

print(time_diff.value_counts().head(10))

timestamp
0 days 01:00:00    145783
Name: count, dtype: int64

In [240]:
print(df[["timestamp", "demand_mw"]].head(50).to_string(index=False))

          timestamp  demand_mw
2010-01-01 00:00:00    36566.5
2010-01-01 01:00:00    35852.5
2010-01-01 02:00:00    34189.5
2010-01-01 03:00:00    32453.0
2010-01-01 04:00:00    30450.5
2010-01-01 05:00:00    29491.5
2010-01-01 06:00:00    29487.5
2010-01-01 07:00:00    28793.5
2010-01-01 08:00:00    28993.5
2010-01-01 09:00:00    31851.5
2010-01-01 10:00:00    35109.0
2010-01-01 11:00:00    37474.0
2010-01-01 12:00:00    38790.0
2010-01-01 13:00:00    38810.5
2010-01-01 14:00:00    38698.0
2010-01-01 15:00:00    39318.5
2010-01-01 16:00:00    42980.0
2010-01-01 17:00:00    45373.5
2010-01-01 18:00:00    44358.0
2010-01-01 19:00:00    42522.5
2010-01-01 20:00:00    41175.5
2010-01-01 21:00:00    39101.5
2010-01-01 22:00:00    36467.5
2010-01-01 23:00:00    34146.0
2010-01-02 00:00:00    34263.5
2010-01-02 01:00:00    33214.0
2010-01-02 02:00:00    32274.0
2010-01-02 03:00:00    31433.0
2010-01-02 04:00:00    29937.5
2010-01-02 05:00:00    29569.0
2010-01-02 06:00:00    30480.0
2010-01-02 07:00:00    31451.5
2010-01-02 08:00:00    33637.5
2010-01-02 09:00:00    37572.0
2010-01-02 10:00:00    40020.0
2010-01-02 11:00:00    41172.5
2010-01-02 12:00:00    41602.0
2010-01-02 13:00:00    41308.5
2010-01-02 14:00:00    41386.0
2010-01-02 15:00:00    42068.0
2010-01-02 16:00:00    46424.5
2010-01-02 17:00:00    49420.5
2010-01-02 18:00:00    48045.5
2010-01-02 19:00:00    45694.0
2010-01-02 20:00:00    43197.0
2010-01-02 21:00:00    40415.0
2010-01-02 22:00:00    38003.5
2010-01-02 23:00:00    35615.5
2010-01-03 00:00:00    35378.5
2010-01-03 01:00:00    34032.5

In [241]:
print(df[["timestamp", "demand_mw"]].tail(50).to_string(index=False))

          timestamp  demand_mw
2026-08-17 06:00:00    21056.5
2026-08-17 07:00:00    24422.0
2026-08-17 08:00:00    25641.0
2026-08-17 09:00:00    26044.0
2026-08-17 10:00:00    25518.0
2026-08-17 11:00:00    25351.0
2026-08-17 12:00:00    25235.5
2026-08-17 13:00:00    24877.0
2026-08-17 14:00:00    24371.0
2026-08-17 15:00:00    24681.0
2026-08-17 16:00:00    26258.0
2026-08-17 17:00:00    27972.0
2026-08-17 18:00:00    28966.5
2026-08-17 19:00:00    29104.0
2026-08-17 20:00:00    28868.0
2026-08-17 21:00:00    27549.5
2026-08-17 22:00:00    25471.0
2026-08-17 23:00:00    23204.5
2026-08-18 00:00:00    22289.5
2026-08-18 01:00:00    21120.5
2026-08-18 02:00:00    20851.0
2026-08-18 03:00:00    19761.5
2026-08-18 04:00:00    19269.5
2026-08-18 05:00:00    19483.0
2026-08-18 06:00:00    21692.0
2026-08-18 07:00:00    24349.5
2026-08-18 08:00:00    25918.0
2026-08-18 09:00:00    25974.0
2026-08-18 10:00:00    24990.0
2026-08-18 11:00:00    24198.0
2026-08-18 12:00:00    24000.0
2026-08-18 13:00:00    22898.5
2026-08-18 14:00:00    22532.0
2026-08-18 15:00:00    23026.0
2026-08-18 16:00:00    24678.5
2026-08-18 17:00:00    26598.5
2026-08-18 18:00:00    28084.0
2026-08-18 19:00:00    28833.5
2026-08-18 20:00:00    28354.0
2026-08-18 21:00:00    27059.5
2026-08-18 22:00:00    24935.5
2026-08-18 23:00:00    22648.0
2026-08-19 00:00:00    22416.5
2026-08-19 01:00:00    22143.5
2026-08-19 02:00:00    21657.0
2026-08-19 03:00:00    20840.5
2026-08-19 04:00:00    20039.5
2026-08-19 05:00:00    19892.0
2026-08-19 06:00:00    21752.0
2026-08-19 07:00:00    24412.5

In [242]:
time_diff = df["timestamp"].diff()

print(
    df.loc[
        time_diff > pd.Timedelta(hours=1),
        ["timestamp", "demand_mw"]
    ].head(30).to_string(index=False)
)

Empty DataFrame
Columns: [timestamp, demand_mw]
Index: []

In [243]:
print("Number of rows:", len(df))
print("Start:", df["timestamp"].min())
print("End:", df["timestamp"].max())

Number of rows: 145784
Start: 2010-01-01 00:00:00
End: 2026-08-19 07:00:00

In [244]:
print(
    "Continuous hourly intervals:",
    (time_diff == pd.Timedelta(hours=1)).sum()
)

Continuous hourly intervals: 145783

In [245]:
print(
    df["timestamp"].dt.date.nunique()
)

6075

In [246]:
print(
    df["timestamp"].dt.year.value_counts().sort_index()
)

timestamp
2010    8760
2011    8760
2012    8784
2013    8760
2014    8760
2015    8760
2016    8784
2017    8760
2018    8760
2019    8760
2020    8784
2021    8760
2022    8760
2023    8760
2024    8784
2025    8760
2026    5528
Name: count, dtype: int64